# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 02:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('touchscreenrest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='numberOfShow',
            new_name='numberOfShows',
        ),
        migrations.RemoveField(
            model_name='image',
            name='isAccomodationLogo',
        ),
        migrations.RemoveField(
            model_name='image',
            name='isRestaurantLogo',
        ),
        migrations.AddField(
            model_name='accomodation',
            name='logo',
            field=models.ImageField(null=True, upload_to='accomodation_logos/'),
        ),
        migrations.AddField(
            model_name='accomodation',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisementActivity', to='touchscreenrest.Activity'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='highlighted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='orderTopDeal',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisementPeriod', to='touchscreenrest.Period'),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='fromEventDate',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='event',
            name='untilEventDate',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='image',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagePeriod', to='touchscreenrest.Period'),
        ),
        migrations.AddField(
            model_name='map',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapTour', to='touchscreenrest.Tour'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(null=True, upload_to='restaurant_logos/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='video',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videoPeriod', to='touchscreenrest.Period'),
        ),
        migrations.AlterField(
            model_name='image',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imageRestaurant', to='touchscreenrest.Restaurant'),
        ),
        migrations.AlterField(
            model_name='map',
            name='accomodation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapAccomodation', to='touchscreenrest.Accomodation'),
        ),
    ]
