# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touchscreenrest', '0002_auto_20170315_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='company',
            field=models.CharField(default='', max_length=200),
        ),
    ]
