# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('touchscreenrest', '0003_advertisement_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='accomodation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imageAccomodation', to='touchscreenrest.Accomodation'),
        ),
        migrations.AlterField(
            model_name='image',
            name='advertisement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imageAdvertisement', to='touchscreenrest.Advertisement'),
        ),
        migrations.AlterField(
            model_name='image',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imageDestination', to='touchscreenrest.Destination'),
        ),
        migrations.AlterField(
            model_name='image',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imageEvent', to='touchscreenrest.Event'),
        ),
        migrations.AlterField(
            model_name='image',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagePeriod', to='touchscreenrest.Period'),
        ),
        migrations.AlterField(
            model_name='image',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imageRestaurant', to='touchscreenrest.Restaurant'),
        ),
        migrations.AlterField(
            model_name='image',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imageTour', to='touchscreenrest.Tour'),
        ),
    ]
