# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 23:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touchscreenrest', '0005_auto_20170316_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomodation',
            name='numberOfClicks',
            field=models.IntegerField(default=0, verbose_name='Number of clicks'),
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Accomodation order display'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='numberOfClicks',
            field=models.IntegerField(default=0, verbose_name='Number of clicks'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='highlighted',
            field=models.BooleanField(default=False, verbose_name='In featured ads?'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='inTopDeal',
            field=models.BooleanField(default=False, verbose_name='In top deals?'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='numberOfClicks',
            field=models.IntegerField(default=0, verbose_name='Number of clicks'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='numberOfShows',
            field=models.IntegerField(default=0, verbose_name='Number of shows'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='orderTopDeal',
            field=models.IntegerField(default=1, verbose_name='Top deal order display'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='numberOfClicks',
            field=models.IntegerField(default=0, verbose_name='Number of clicks'),
        ),
        migrations.AlterField(
            model_name='event',
            name='fromEventDate',
            field=models.DateField(default=datetime.datetime.now, verbose_name='From event date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='numberOfClicks',
            field=models.IntegerField(default=0, verbose_name='Number of clicks'),
        ),
        migrations.AlterField(
            model_name='event',
            name='untilEventDate',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Until event date'),
        ),
        migrations.AlterField(
            model_name='period',
            name='numberOfClicks',
            field=models.IntegerField(default=0, verbose_name='Number of clicks'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='numberOfClicks',
            field=models.IntegerField(default=0, verbose_name='Number of clicks'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Restaurant order display'),
        ),
    ]
