# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touchscreenrest', '0006_auto_20170316_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='highlighted',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='In featured ads?'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='inTopDeal',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='In top deals?'),
        ),
    ]
