# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touchscreenrest', '0007_auto_20170317_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomodation',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Accomodation order display'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='orderTopDeal',
            field=models.IntegerField(default=0, verbose_name='Top deal order display'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Restaurant order display'),
        ),
    ]
