# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 23:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('touchscreenrest', '0010_auto_20170321_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imageActivity', to='touchscreenrest.Activity'),
        ),
        migrations.AddField(
            model_name='tour',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tourAcvitity', to='touchscreenrest.Activity'),
        ),
        migrations.AddField(
            model_name='tour',
            name='address',
            field=models.CharField(default='dis', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='email',
            field=models.EmailField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='phone',
            field=models.CharField(default='', max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videoActivity', to='touchscreenrest.Activity'),
        ),
    ]
