# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 01:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('touchscreenrest', '0014_auto_20170327_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='activityDestination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisementActivityDestination', to='touchscreenrest.ActivityDestination', verbose_name='Destination for Activity'),
        ),
        migrations.AlterField(
            model_name='image',
            name='activityDestination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imageActivityDestination', to='touchscreenrest.ActivityDestination', verbose_name='Destination for Activity'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='activityDestination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tourActivityDestination', to='touchscreenrest.ActivityDestination', verbose_name='Destination for Activity'),
        ),
        migrations.AlterField(
            model_name='video',
            name='activityDestination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videoActivityDestination', to='touchscreenrest.ActivityDestination', verbose_name='Destination for Activity'),
        ),
    ]
