# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 01:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('touchscreenrest', '0015_auto_20170327_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapDestination', to='touchscreenrest.Destination'),
        ),
    ]
