# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 01:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('touchscreenrest', '0016_map_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventPeriod', to='touchscreenrest.Period'),
        ),
    ]
