# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 04:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('touchscreenrest', '0017_auto_20170405_0134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ['pk']},
        ),
    ]
