# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 00:33
from __future__ import unicode_literals

from django.db import migrations, models
import touchscreenrest.models


class Migration(migrations.Migration):

    dependencies = [
        ('touchscreenrest', '0018_auto_20170405_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomodation',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='essentialservice',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mining',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='retail',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transportation',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='phone',
            field=models.CharField(max_length=16, validators=[touchscreenrest.models.validate_phone]),
        ),
        migrations.AlterField(
            model_name='essentialservice',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='essentialservice',
            name='phone',
            field=models.CharField(max_length=16, validators=[touchscreenrest.models.validate_phone]),
        ),
        migrations.AlterField(
            model_name='mining',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mining',
            name='phone',
            field=models.CharField(max_length=16, validators=[touchscreenrest.models.validate_phone]),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(max_length=16, validators=[touchscreenrest.models.validate_phone]),
        ),
        migrations.AlterField(
            model_name='retail',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='retail',
            name='phone',
            field=models.CharField(max_length=16, validators=[touchscreenrest.models.validate_phone]),
        ),
        migrations.AlterField(
            model_name='tour',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='phone',
            field=models.CharField(max_length=16, validators=[touchscreenrest.models.validate_phone]),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='phone',
            field=models.CharField(max_length=16, validators=[touchscreenrest.models.validate_phone]),
        ),
    ]
