# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 00:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('touchscreenrest', '0021_auto_20170407_0059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={},
        ),
    ]
