# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 23:41
from __future__ import unicode_literals

from django.db import migrations, models
import touchscreenrest.models


class Migration(migrations.Migration):

    dependencies = [
        ('touchscreenrest', '0023_auto_20170407_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[touchscreenrest.models.validate_phone]),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
