# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 00:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('touchscreenrest', '0024_auto_20170409_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('numberOfClicks', models.IntegerField(default=0, verbose_name='Number of clicks')),
            ],
            options={
                'verbose_name': 'Services Subsection 2',
                'verbose_name_plural': 'Services Subsection 2',
            },
        ),
        migrations.AlterField(
            model_name='essentialservice',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='essentialServiceDestination', to='touchscreenrest.Destination'),
        ),
        migrations.AlterField(
            model_name='mining',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='miningDestination', to='touchscreenrest.Destination'),
        ),
        migrations.AlterField(
            model_name='retail',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retailDestination', to='touchscreenrest.Destination'),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transportationDestination', to='touchscreenrest.Destination'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='serviceType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisementServiceType', to='touchscreenrest.ServiceType', verbose_name='Services Subsection 2'),
        ),
        migrations.AddField(
            model_name='essentialservice',
            name='serviceType',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='essentialServiceServiceType', to='touchscreenrest.ServiceType', verbose_name='Services Subsection 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='serviceType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imageServiceType', to='touchscreenrest.ServiceType', verbose_name='Services Subsection 2'),
        ),
        migrations.AddField(
            model_name='mining',
            name='serviceType',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='miningServiceType', to='touchscreenrest.ServiceType', verbose_name='Services Subsection 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retail',
            name='serviceType',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='retailServiceType', to='touchscreenrest.ServiceType', verbose_name='Services Subsection 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportation',
            name='serviceType',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='transportationServiceType', to='touchscreenrest.ServiceType', verbose_name='Services Subsection 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='serviceType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videoServiceType', to='touchscreenrest.ServiceType', verbose_name='Services Subsection 2'),
        ),
    ]
