# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 01:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('touchscreenrest', '0025_auto_20170410_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essentialservice',
            name='serviceType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='essentialServiceServiceType', to='touchscreenrest.ServiceType', verbose_name='Services Subsection 2'),
        ),
        migrations.AlterField(
            model_name='mining',
            name='serviceType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='miningServiceType', to='touchscreenrest.ServiceType', verbose_name='Services Subsection 2'),
        ),
        migrations.AlterField(
            model_name='retail',
            name='serviceType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retailServiceType', to='touchscreenrest.ServiceType', verbose_name='Services Subsection 2'),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='serviceType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transportationServiceType', to='touchscreenrest.ServiceType', verbose_name='Services Subsection 2'),
        ),
    ]
