# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 06:22
from __future__ import unicode_literals

from django.db import migrations, models
import touchscreenrest.models


class Migration(migrations.Migration):

    dependencies = [
        ('touchscreenrest', '0026_auto_20170410_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essentialservice',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='essentialservice',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='essentialservice',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[touchscreenrest.models.validate_phone]),
        ),
        migrations.AlterField(
            model_name='mining',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='mining',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mining',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[touchscreenrest.models.validate_phone]),
        ),
        migrations.AlterField(
            model_name='retail',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='retail',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='retail',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[touchscreenrest.models.validate_phone]),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[touchscreenrest.models.validate_phone]),
        ),
    ]
