# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touchscreenrest', '0027_auto_20170410_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essentialservice',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='essential_services_logos/'),
        ),
    ]
