# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 06:07
from __future__ import unicode_literals

from django.db import migrations, models
import touchscreenrest.models


class Migration(migrations.Migration):

    dependencies = [
        ('touchscreenrest', '0028_auto_20170410_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitydestination',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tour',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[touchscreenrest.models.validate_phone]),
        ),
    ]
