# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 06:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('touchscreenrest', '0029_auto_20170411_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitydestination',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activityDestinationDestination', to='touchscreenrest.Destination'),
        ),
    ]
