# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touchscreenrest', '0030_activitydestination_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='airport',
            field=models.CharField(default='', max_length=200, verbose_name='Closest Airport'),
        ),
        migrations.AddField(
            model_name='destination',
            name='province',
            field=models.CharField(default='', max_length=200),
        ),
    ]
