# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 01:49
from __future__ import unicode_literals

from django.db import migrations, models
import touchscreenrest.models


class Migration(migrations.Migration):

    dependencies = [
        ('touchscreenrest', '0031_auto_20170412_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Event Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[touchscreenrest.models.validate_phone]),
        ),
        migrations.AddField(
            model_name='event',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
