# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 06:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('touchscreenrest', '0032_auto_20170412_0149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='retail',
            options={'verbose_name': 'Retail & Service'},
        ),
    ]
