# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 00:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('touchscreenrest', '0033_auto_20170413_0656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitydestination',
            options={'verbose_name': 'Destination for Activity', 'verbose_name_plural': 'Destination for Activities'},
        ),
    ]
