# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touchscreenrest', '0034_auto_20170427_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='cards',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Cards accepted'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='courtesy',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Courtesy Parking'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cuisine',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='parking',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Secure Parking'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='price',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Price Guide'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='takeaway',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='wifi',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='WIFI'),
        ),
    ]
