# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touchscreenrest', '0035_auto_20170501_0621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name': 'Dining', 'verbose_name_plural': 'Dining'},
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='wifi',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Wi-Fi'),
        ),
    ]
