# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touchscreenrest', '0038_auto_20170503_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='takeawayOther',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Take-away Additional Info'),
        ),
    ]
