# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touchscreenrest', '0041_auto_20170503_0152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='fromEventDate',
        ),
        migrations.RemoveField(
            model_name='event',
            name='untilEventDate',
        ),
        migrations.AddField(
            model_name='event',
            name='eventDate',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Date of event'),
        ),
        migrations.AddField(
            model_name='event',
            name='eventMonth',
            field=models.CharField(blank=True, choices=[('JANUARY', 'JANUARY'), ('FEBRUARY', 'FEBRUARY'), ('MARCH', 'MARCH'), ('APRIL', 'APRIL'), ('MAY', 'MAY'), ('JUNE', 'JUNE'), ('JULY', 'JULY'), ('AUGUST', 'AUGUST'), ('SEPTEMBER', 'SEPTEMBER'), ('OCTOBER', 'OCTOBER'), ('NOVEMBER', 'NOVEMBER'), ('DECEMBER', 'DECEMBER')], max_length=10, null=True, verbose_name='Month of event'),
        ),
    ]
