# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touchscreenrest', '0042_auto_20170518_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomodation',
            name='phone',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='essentialservice',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='mining',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='retail',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
