# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touchscreenrest', '0043_auto_20170519_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='display',
            field=models.CharField(choices=[('NOT_DISPLAY', 'DO NOT DISPLAY'), ('INDEFINITE', 'INDEFINITE'), ('OTHER', 'OTHER')], default='INDEFINITE', max_length=11),
        ),
        migrations.AddField(
            model_name='activity',
            name='displayFrom',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='displayTo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
