# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touchscreenrest', '0044_auto_20170523_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomodation',
            name='display',
            field=models.CharField(choices=[('NOT_DISPLAY', 'DO NOT DISPLAY'), ('INDEFINITE', 'INDEFINITE'), ('SPECIFY', 'SPECIFY')], default='INDEFINITE', max_length=11),
        ),
        migrations.AddField(
            model_name='accomodation',
            name='displayFrom',
            field=models.DateField(blank=True, null=True, verbose_name='Start display from'),
        ),
        migrations.AddField(
            model_name='accomodation',
            name='displayTo',
            field=models.DateField(blank=True, null=True, verbose_name='Stop display from'),
        ),
        migrations.AddField(
            model_name='activitydestination',
            name='display',
            field=models.CharField(choices=[('NOT_DISPLAY', 'DO NOT DISPLAY'), ('INDEFINITE', 'INDEFINITE'), ('SPECIFY', 'SPECIFY')], default='INDEFINITE', max_length=11),
        ),
        migrations.AddField(
            model_name='activitydestination',
            name='displayFrom',
            field=models.DateField(blank=True, null=True, verbose_name='Start display from'),
        ),
        migrations.AddField(
            model_name='activitydestination',
            name='displayTo',
            field=models.DateField(blank=True, null=True, verbose_name='Stop display from'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='display',
            field=models.CharField(choices=[('NOT_DISPLAY', 'DO NOT DISPLAY'), ('INDEFINITE', 'INDEFINITE'), ('SPECIFY', 'SPECIFY')], default='INDEFINITE', max_length=11),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='displayFrom',
            field=models.DateField(blank=True, null=True, verbose_name='Start display from'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='displayTo',
            field=models.DateField(blank=True, null=True, verbose_name='Stop display from'),
        ),
        migrations.AddField(
            model_name='destination',
            name='display',
            field=models.CharField(choices=[('NOT_DISPLAY', 'DO NOT DISPLAY'), ('INDEFINITE', 'INDEFINITE'), ('SPECIFY', 'SPECIFY')], default='INDEFINITE', max_length=11),
        ),
        migrations.AddField(
            model_name='destination',
            name='displayFrom',
            field=models.DateField(blank=True, null=True, verbose_name='Start display from'),
        ),
        migrations.AddField(
            model_name='destination',
            name='displayTo',
            field=models.DateField(blank=True, null=True, verbose_name='Stop display from'),
        ),
        migrations.AddField(
            model_name='essentialservice',
            name='display',
            field=models.CharField(choices=[('NOT_DISPLAY', 'DO NOT DISPLAY'), ('INDEFINITE', 'INDEFINITE'), ('SPECIFY', 'SPECIFY')], default='INDEFINITE', max_length=11),
        ),
        migrations.AddField(
            model_name='essentialservice',
            name='displayFrom',
            field=models.DateField(blank=True, null=True, verbose_name='Start display from'),
        ),
        migrations.AddField(
            model_name='essentialservice',
            name='displayTo',
            field=models.DateField(blank=True, null=True, verbose_name='Stop display from'),
        ),
        migrations.AddField(
            model_name='event',
            name='display',
            field=models.CharField(choices=[('NOT_DISPLAY', 'DO NOT DISPLAY'), ('INDEFINITE', 'INDEFINITE'), ('SPECIFY', 'SPECIFY')], default='INDEFINITE', max_length=11),
        ),
        migrations.AddField(
            model_name='event',
            name='displayFrom',
            field=models.DateField(blank=True, null=True, verbose_name='Start display from'),
        ),
        migrations.AddField(
            model_name='event',
            name='displayTo',
            field=models.DateField(blank=True, null=True, verbose_name='Stop display from'),
        ),
        migrations.AddField(
            model_name='mining',
            name='display',
            field=models.CharField(choices=[('NOT_DISPLAY', 'DO NOT DISPLAY'), ('INDEFINITE', 'INDEFINITE'), ('SPECIFY', 'SPECIFY')], default='INDEFINITE', max_length=11),
        ),
        migrations.AddField(
            model_name='mining',
            name='displayFrom',
            field=models.DateField(blank=True, null=True, verbose_name='Start display from'),
        ),
        migrations.AddField(
            model_name='mining',
            name='displayTo',
            field=models.DateField(blank=True, null=True, verbose_name='Stop display from'),
        ),
        migrations.AddField(
            model_name='period',
            name='display',
            field=models.CharField(choices=[('NOT_DISPLAY', 'DO NOT DISPLAY'), ('INDEFINITE', 'INDEFINITE'), ('SPECIFY', 'SPECIFY')], default='INDEFINITE', max_length=11),
        ),
        migrations.AddField(
            model_name='period',
            name='displayFrom',
            field=models.DateField(blank=True, null=True, verbose_name='Start display from'),
        ),
        migrations.AddField(
            model_name='period',
            name='displayTo',
            field=models.DateField(blank=True, null=True, verbose_name='Stop display from'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='display',
            field=models.CharField(choices=[('NOT_DISPLAY', 'DO NOT DISPLAY'), ('INDEFINITE', 'INDEFINITE'), ('SPECIFY', 'SPECIFY')], default='INDEFINITE', max_length=11),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='displayFrom',
            field=models.DateField(blank=True, null=True, verbose_name='Start display from'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='displayTo',
            field=models.DateField(blank=True, null=True, verbose_name='Stop display from'),
        ),
        migrations.AddField(
            model_name='retail',
            name='display',
            field=models.CharField(choices=[('NOT_DISPLAY', 'DO NOT DISPLAY'), ('INDEFINITE', 'INDEFINITE'), ('SPECIFY', 'SPECIFY')], default='INDEFINITE', max_length=11),
        ),
        migrations.AddField(
            model_name='retail',
            name='displayFrom',
            field=models.DateField(blank=True, null=True, verbose_name='Start display from'),
        ),
        migrations.AddField(
            model_name='retail',
            name='displayTo',
            field=models.DateField(blank=True, null=True, verbose_name='Stop display from'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='display',
            field=models.CharField(choices=[('NOT_DISPLAY', 'DO NOT DISPLAY'), ('INDEFINITE', 'INDEFINITE'), ('SPECIFY', 'SPECIFY')], default='INDEFINITE', max_length=11),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='displayFrom',
            field=models.DateField(blank=True, null=True, verbose_name='Start display from'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='displayTo',
            field=models.DateField(blank=True, null=True, verbose_name='Stop display from'),
        ),
        migrations.AddField(
            model_name='tour',
            name='display',
            field=models.CharField(choices=[('NOT_DISPLAY', 'DO NOT DISPLAY'), ('INDEFINITE', 'INDEFINITE'), ('SPECIFY', 'SPECIFY')], default='INDEFINITE', max_length=11),
        ),
        migrations.AddField(
            model_name='tour',
            name='displayFrom',
            field=models.DateField(blank=True, null=True, verbose_name='Start display from'),
        ),
        migrations.AddField(
            model_name='tour',
            name='displayTo',
            field=models.DateField(blank=True, null=True, verbose_name='Stop display from'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='display',
            field=models.CharField(choices=[('NOT_DISPLAY', 'DO NOT DISPLAY'), ('INDEFINITE', 'INDEFINITE'), ('SPECIFY', 'SPECIFY')], default='INDEFINITE', max_length=11),
        ),
        migrations.AddField(
            model_name='transportation',
            name='displayFrom',
            field=models.DateField(blank=True, null=True, verbose_name='Start display from'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='displayTo',
            field=models.DateField(blank=True, null=True, verbose_name='Stop display from'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='display',
            field=models.CharField(choices=[('NOT_DISPLAY', 'DO NOT DISPLAY'), ('INDEFINITE', 'INDEFINITE'), ('SPECIFY', 'SPECIFY')], default='INDEFINITE', max_length=11),
        ),
        migrations.AlterField(
            model_name='activity',
            name='displayFrom',
            field=models.DateField(blank=True, null=True, verbose_name='Start display from'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='displayTo',
            field=models.DateField(blank=True, null=True, verbose_name='Stop display from'),
        ),
    ]
