# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touchscreenrest', '0045_auto_20170523_0617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accomodation',
            options={'ordering': ['order'], 'verbose_name': 'Accommodation', 'verbose_name_plural': 'Accommodation'},
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['order'], 'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='activitydestination',
            options={'ordering': ['order'], 'verbose_name': 'Destination for Activity', 'verbose_name_plural': 'Destination for Activities'},
        ),
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='essentialservice',
            options={'ordering': ['order'], 'verbose_name': 'Essential Service'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='map',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='mining',
            options={'ordering': ['order'], 'verbose_name': 'Mining & Resource'},
        ),
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['order'], 'verbose_name': 'Dining', 'verbose_name_plural': 'Dining'},
        ),
        migrations.AlterModelOptions(
            name='retail',
            options={'ordering': ['order'], 'verbose_name': 'Retail & Service'},
        ),
        migrations.AlterModelOptions(
            name='servicetype',
            options={'ordering': ['order'], 'verbose_name': 'Services Subsection 2', 'verbose_name_plural': 'Services Subsection 2'},
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='transportation',
            options={'ordering': ['order'], 'verbose_name': 'Car Hire & Transport', 'verbose_name_plural': 'Car Hire & Transport'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['pk']},
        ),
        migrations.AddField(
            model_name='activity',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Activity order display'),
        ),
        migrations.AddField(
            model_name='activitydestination',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Destination for Activity order display'),
        ),
        migrations.AddField(
            model_name='destination',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Destination order display'),
        ),
        migrations.AddField(
            model_name='event',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Events order display'),
        ),
        migrations.AddField(
            model_name='period',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Period order display'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Services Subsection 2 order display'),
        ),
        migrations.AddField(
            model_name='tour',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Tour order display'),
        ),
    ]
