# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 04:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('touchscreenrest', '0046_auto_20170601_0351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accomodation',
            options={'ordering': ['order', 'pk'], 'verbose_name': 'Accommodation', 'verbose_name_plural': 'Accommodation'},
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['order', 'pk'], 'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='activitydestination',
            options={'ordering': ['order', 'pk'], 'verbose_name': 'Destination for Activity', 'verbose_name_plural': 'Destination for Activities'},
        ),
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ['order', 'pk']},
        ),
        migrations.AlterModelOptions(
            name='essentialservice',
            options={'ordering': ['order', 'pk'], 'verbose_name': 'Essential Service'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['order', 'pk']},
        ),
        migrations.AlterModelOptions(
            name='mining',
            options={'ordering': ['order', 'pk'], 'verbose_name': 'Mining & Resource'},
        ),
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ['order', 'pk']},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['order', 'pk'], 'verbose_name': 'Dining', 'verbose_name_plural': 'Dining'},
        ),
        migrations.AlterModelOptions(
            name='retail',
            options={'ordering': ['order', 'pk'], 'verbose_name': 'Retail & Service'},
        ),
        migrations.AlterModelOptions(
            name='servicetype',
            options={'ordering': ['order', 'pk'], 'verbose_name': 'Services Subsection 2', 'verbose_name_plural': 'Services Subsection 2'},
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ['order', 'pk']},
        ),
        migrations.AlterModelOptions(
            name='transportation',
            options={'ordering': ['order', 'pk'], 'verbose_name': 'Car Hire & Transport', 'verbose_name_plural': 'Car Hire & Transport'},
        ),
    ]
