# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touchscreenrest', '0048_accomodation_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='firstLevelAd',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Is Level One Ad?'),
        ),
    ]
