# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touchscreenrest', '0052_airport_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='redirectTo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Redirect advertisement to'),
        ),
    ]
