# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touchscreenrest', '0055_video_numberofshows'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='mapType',
            field=models.CharField(choices=[('CITY', 'CITY MAP'), ('COUNTRY', 'COUNTRY MAP')], default='COUNTRY', max_length=7, verbose_name='Map Type'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
