# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touchscreenrest', '0056_auto_20170620_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='service_type_icons/'),
        ),
    ]
