# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touchscreenrest', '0058_auto_20170622_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='activity_icons/'),
        ),
    ]
