# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 00:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('touchscreenrest', '0059_activity_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(default='')),
                ('order', models.IntegerField(default=0, verbose_name='Section order display')),
                ('numberOfClicks', models.IntegerField(default=0, verbose_name='Number of clicks')),
                ('display', models.CharField(choices=[('NOT_DISPLAY', 'DO NOT DISPLAY'), ('INDEFINITE', 'INDEFINITE'), ('SPECIFY', 'SPECIFY')], default='INDEFINITE', max_length=11)),
                ('displayFrom', models.DateField(blank=True, null=True, verbose_name='Start display from')),
                ('displayTo', models.DateField(blank=True, null=True, verbose_name='Stop display from')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Trivia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0, verbose_name='Trivia order display')),
                ('numberOfClicks', models.IntegerField(default=0, verbose_name='Number of clicks')),
                ('display', models.CharField(choices=[('NOT_DISPLAY', 'DO NOT DISPLAY'), ('INDEFINITE', 'INDEFINITE'), ('SPECIFY', 'SPECIFY')], default='INDEFINITE', max_length=11)),
                ('displayFrom', models.DateField(blank=True, null=True, verbose_name='Start display from')),
                ('displayTo', models.DateField(blank=True, null=True, verbose_name='Stop display from')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='section',
            name='trivia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sectionTrivia', to='touchscreenrest.Trivia'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='trivia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triviaAdvertisement', to='touchscreenrest.Trivia'),
        ),
        migrations.AddField(
            model_name='image',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imageSection', to='touchscreenrest.Section'),
        ),
        migrations.AddField(
            model_name='image',
            name='trivia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imageTrivia', to='touchscreenrest.Trivia'),
        ),
    ]
